### PR TITLE
Updates to imaging

### PR DESCRIPTION
**Pull request by adamkglaser**
Updating imaging acquisition and instrument. @saskiad the biggest change is splitting out some of the acquisition parameters from lasers to a new daq object. As we discussed, these are input variables that dictate the waveforms we play to various devices on the SPIM systems. This is highly system specific, and is different for all of our systems. What is the best way to reflect this in the JSON? To list all of them out explicitly but make none of them 'required'? If so, I'll need to add them all in.

### CODE REVIEW

**Comment by dyf** [comment]
@adamkglaser If you decide not to model thing explicitly, you can do something like this if you just want to say "this is a dictionary":

                "parameters": {
                    "type ": "object",
                    "title": "Parameters",
                    "properties": {},
                    "additionalProperties": true,
                    "description": "Parameters or configs used for process"
                },

**Comment by adamkglaser** [comment]
Updated with the above per @dyf suggestion. It should be ready to review and merge now.

**Comment by saskiad** [comment]
are you confident that people will provide them if they aren't listed explicitly?

**Comment by adamkglaser** [comment]
These waveform parameters we will auto-fill from the GUI and system configuration file for a given scan. So luckily these should not involve any user input (!)

**Review by saskiad — COMMENTED** [review]
looks good to me

**Pull request merged**
