### PR TITLE
Subject schema

### PR DESCRIPTION
**Pull request by saskiad**
Replace mouse schema with subject schema.

### CODE REVIEW

**Review by dyf — COMMENTED** [review]
@saskiad this looks the same as PR #14.  Is that intentional?

**Comment by saskiad** [comment]
No. this is a new file altogether.

**Comment by saskiad** [comment]
oh, it somehow has 4 previous commits in it... that's weird. I clearly don't know how to do a pull request properly.

**Comment by dyf** [comment]
I'll walk you through it later.  I would say go ahead and merge all these.

**Pull request merged**
